chore: add briefcase removal script
Zextras/carbonio-build pull request #51
Opened 2023-04-11 09:37 UTC by Polpetta

CO-625

2023-04-12 07:49 UTC, keshavbhatt approved these changes

2023-04-18 12:29 UTC, aheeva-yuliya approved these changes

2023-04-19 13:55 UTC, frisonisland approved these changes

2023-05-12 07:46 UTC, Polpetta commented
![image](https://github.com/Zextras/carbonio-build/assets/5928183/1a668d7e-048e-4380-bb5d-a029e2ad9b20)
Shouldn't we merge in `devel` right?

2023-05-12 08:17 UTC, frisonisland commented
> ![image](https://user-images.githubusercontent.com/5928183/237905122-1a668d7e-048e-4380-bb5d-a029e2ad9b20.png) Shouldn't we merge in `devel` right?

Yes! devel only

2023-05-12 09:31 UTC, keshavbhatt requested changes
should target devel.

2023-05-12 11:07 UTC, keshavbhatt approved these changes

2023-05-12 12:38 UTC, merged